  import 'package:gain_wave_app/Views/Performance/Model/exerciseModel.dart';

final List<Exercise> exercises = [
  Exercise(
    id: '1',
    name: 'Bench Press',
    description: 'Lie on a flat bench and press the weight upward until your arms are extended.',
    imageUrl: 'assets/images/bench_press.png',
    targetMuscle: 'Chest',
    equipment: 'Barbell, Bench',
    defaultReps: 8,
    defaultSets: 3,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '2',
    name: 'Squat',
    description: 'Stand with feet shoulder-width apart, lower your body as if sitting in an invisible chair, then return to standing position.',
    imageUrl: 'assets/images/squat.png',
    targetMuscle: 'Legs',
    equipment: 'Barbell, Squat Rack',
    defaultReps: 10,
    defaultSets: 4,
    defaultRestTime: 120,
  ),
  Exercise(
    id: '3',
    name: 'Pull-Up',
    description: 'Hang from a bar with palms facing away and pull your body up until your chin is over the bar.',
    imageUrl: 'assets/images/pull_up.png',
    targetMuscle: 'Back',
    equipment: 'Pull-Up Bar',
    defaultReps: 8,
    defaultSets: 3,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '4',
    name: 'Deadlift',
    description: 'Bend at the waist and knees to grip a barbell, then stand up straight while keeping the barbell close to your body.',
    imageUrl: 'assets/images/deadlift.png',
    targetMuscle: 'Back',
    equipment: 'Barbell',
    defaultReps: 5,
    defaultSets: 3,
    defaultRestTime: 180,
  ),
  Exercise(
    id: '5',
    name: 'Shoulder Press',
    description: 'Press weights upward from shoulder level until arms are extended overhead.',
    imageUrl: 'assets/images/shoulder_press.png',
    targetMuscle: 'Shoulders',
    equipment: 'Dumbbells',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '6',
    name: 'Bicep Curl',
    description: 'Stand with a dumbbell in each hand at arm\'s length. Keep elbows close to your torso and rotate the palms of your hands until they are facing forward. Curl the weights while keeping your upper arms stationary.',
    imageUrl: 'assets/images/bicep_curl.png',
    targetMuscle: 'Arms',
    equipment: 'Dumbbells',
    defaultReps: 12,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '7',
    name: 'Tricep Dip',
    description: 'Use parallel bars or a bench to lower and raise your body by bending and straightening your arms.',
    imageUrl: 'assets/images/tricep_dip.png',
    targetMuscle: 'Arms',
    equipment: 'Dip Bars, Bench',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '8',
    name: 'Lunges',
    description: 'Step forward with one leg and lower your body until both knees are bent at about a 90-degree angle. Return to start and repeat on the other leg.',
    imageUrl: 'assets/images/lunges.png',
    targetMuscle: 'Legs',
    equipment: 'Bodyweight or Dumbbells',
    defaultReps: 12,
    defaultSets: 3,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '9',
    name: 'Lat Pulldown',
    description: 'Sit at a lat pulldown station and pull the bar down to your chest while keeping your back straight.',
    imageUrl: 'assets/images/lat_pulldown.png',
    targetMuscle: 'Back',
    equipment: 'Lat Pulldown Machine',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '10',
    name: 'Leg Press',
    description: 'Sit on the leg press machine and push the platform away with your feet until your legs are extended.',
    imageUrl: 'assets/images/leg_press.png',
    targetMuscle: 'Legs',
    equipment: 'Leg Press Machine',
    defaultReps: 12,
    defaultSets: 4,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '11',
    name: 'Cable Row',
    description: 'Sit at a cable row machine, pull the handle towards your torso, then return with control.',
    imageUrl: 'assets/images/cable_row.png',
    targetMuscle: 'Back',
    equipment: 'Cable Machine',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '12',
    name: 'Leg Curl',
    description: 'Lie face down on a leg curl machine and curl your legs up towards your glutes.',
    imageUrl: 'assets/images/leg_curl.png',
    targetMuscle: 'Hamstrings',
    equipment: 'Leg Curl Machine',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '13',
    name: 'Leg Extension',
    description: 'Sit on a leg extension machine and extend your legs until they are straight.',
    imageUrl: 'assets/images/leg_extension.png',
    targetMuscle: 'Quadriceps',
    equipment: 'Leg Extension Machine',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '14',
    name: 'Incline Dumbbell Press',
    description: 'Lie on an incline bench and press dumbbells upward until your arms are extended.',
    imageUrl: 'assets/images/incline_dumbbell_press.png',
    targetMuscle: 'Chest',
    equipment: 'Dumbbells, Incline Bench',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 90,
  ),
  Exercise(
    id: '15',
    name: 'Hammer Curl',
    description: 'Hold dumbbells with your palms facing your torso and curl the weights.',
    imageUrl: 'assets/images/hammer_curl.png',
    targetMuscle: 'Arms',
    equipment: 'Dumbbells',
    defaultReps: 12,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '16',
    name: 'Seated Calf Raise',
    description: 'Sit on the machine, place toes on the footplate, and raise your heels as high as possible.',
    imageUrl: 'assets/images/seated_calf_raise.png',
    targetMuscle: 'Calves',
    equipment: 'Seated Calf Machine',
    defaultReps: 15,
    defaultSets: 3,
    defaultRestTime: 45,
  ),
  Exercise(
    id: '17',
    name: 'Russian Twist',
    description: 'Sit on the floor, lean back slightly, lift your feet, and twist your torso from side to side.',
    imageUrl: 'assets/images/russian_twist.png',
    targetMuscle: 'Abs',
    equipment: 'Bodyweight or Medicine Ball',
    defaultReps: 20,
    defaultSets: 3,
    defaultRestTime: 45,
  ),
  Exercise(
    id: '18',
    name: 'Plank',
    description: 'Hold your body in a straight line from head to heels, supported by your forearms and toes.',
    imageUrl: 'assets/images/plank.png',
    targetMuscle: 'Core',
    equipment: 'Bodyweight',
    defaultReps: 1,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '19',
    name: 'Dumbbell Fly',
    description: 'Lie on a flat bench holding dumbbells, extend arms out to sides and bring them together over your chest.',
    imageUrl: 'assets/images/dumbbell_fly.png',
    targetMuscle: 'Chest',
    equipment: 'Dumbbells, Bench',
    defaultReps: 10,
    defaultSets: 3,
    defaultRestTime: 60,
  ),
  Exercise(
    id: '20',
    name: 'Mountain Climbers',
    description: 'Start in plank position and quickly alternate bringing knees to chest.',
    imageUrl: 'assets/images/mountain_climbers.png',
    targetMuscle: 'Full Body',
    equipment: 'Bodyweight',
    defaultReps: 30,
    defaultSets: 3,
    defaultRestTime: 30,
  ),
];
